import type { Metadata } from "next";
import { vazirmatn, FrederickatheGreat } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bake Away",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ direction: "rtl" }}>
      <body
        className={`${vazirmatn.variable} ${FrederickatheGreat.variable} antialiased`}
      >
        {" "}
        <main className="max-w-[450px] bg-[#FAF7F2] overflow-clip mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
