import type { Metadata } from "next";
import { vazirmatn, FrederickatheGreat } from "./font";
import { CartProvider } from "../app/context/cart-context";
import "./globals.css";

export const metadata: Metadata = {
  title: "Crust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ direction: "rtl" }}>
      <body
        className={`${vazirmatn.variable} ${FrederickatheGreat.variable} antialiased`}
      >
        <CartProvider>
          <main className="max-w-[450px] bg-[#F9F3F4] overflow-clip mx-auto h-full">
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
